package java_a_beginners_guide.chapter_sixteen;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

public class CheckBoxDemonstration implements ItemListener {
    //Instance fields.
    JLabel mJLabelSelected;
    JLabel mJLabelChanged;
    JCheckBox mJCheckBoxAlpha;
    JCheckBox mJCheckBoxBeta;
    JCheckBox mJCheckBoxGamma;

    public CheckBoxDemonstration() {
        //Create a new frame container.
        JFrame jFrame = new JFrame("CheckBox Example");

        //Specify FlowLayout for the layout manager.
        jFrame.setLayout(new FlowLayout());

        //Give the frame an initial size.
        jFrame.setSize(280, 120);

        //Terminate the program when the user closes the application.
        jFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //Create empty labels.
        mJLabelChanged = new JLabel("");
        mJLabelSelected = new JLabel("");

        //Make check boxes.
        mJCheckBoxAlpha = new JCheckBox("Alpha");
        mJCheckBoxBeta = new JCheckBox("Beta");
        mJCheckBoxGamma = new JCheckBox("Gamma");

        //Events generated by check boxes are handled in common
        //by the itemStateChanged() method implemented by CheckBoxDemonstration.
        mJCheckBoxAlpha.addItemListener(this);
        mJCheckBoxBeta.addItemListener(this);
        mJCheckBoxGamma.addItemListener(this);

        //Add check boxes and labels to the content pane.
        jFrame.add(mJCheckBoxAlpha);
        jFrame.add(mJCheckBoxBeta);
        jFrame.add(mJCheckBoxGamma);
        jFrame.add(mJLabelChanged);
        jFrame.add(mJLabelSelected);

        //Display the frame.
        jFrame.setVisible(true);
    }

    //This is the handler for the item boxes.
    @Override
    public void itemStateChanged(ItemEvent itemEvent) {
        String string = "";

        //Obtain a reference to the checkbox that caused the event.
        JCheckBox checkBox = (JCheckBox) itemEvent.getItem();

        //Report what checkbox has changed.
        if(checkBox.isSelected()) {
            mJLabelChanged.setText(checkBox.getText() + " was just selected");
        }else {
            mJLabelChanged.setText(checkBox.getText() + " was just cleared");
        }

        //Report all selected boxes.
        if(mJCheckBoxAlpha.isSelected()) {
            string += "Alpha ";
        }
        if(mJCheckBoxBeta.isSelected()) {
            string += "Beta ";
        }
        if(mJCheckBoxGamma.isSelected()) {
            string += "Gamma ";
        }

        mJLabelSelected.setText("Selected Check boxes: " + string);
    }

    public static void main(String[] args) {
        //Create the frame on the event dispatching thread.
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CheckBoxDemonstration();
            }
        });
    }
}
